import { Navbar } from '@/components/Navbar';
import { Card, CardContent } from '@/components/ui/card';
import { Briefcase, LineChart, HandCoins } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Link } from 'react-router-dom';
import { CLUBS } from '@/data/clubs';

export default function Investment() {
  const fundingClubs = CLUBS.filter(c => c.funding);

  return (
    <div className="min-h-screen bg-background flex flex-col font-sans">
      <Navbar />
      
      <section className="pt-24 pb-16 bg-black text-white px-4 relative overflow-hidden">
        <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1522778119026-d647f0596c20?ixlib=rb-4.0.3&auto=format&fit=crop&w=2000&q=80')] bg-cover bg-center opacity-20"></div>
        <div className="absolute inset-0 bg-gradient-to-t from-black to-transparent"></div>
        <div className="container mx-auto max-w-4xl text-center relative z-10">
          <h1 className="text-5xl font-bold tracking-tighter mb-6">Investment & Ownership</h1>
          <p className="text-xl text-gray-400 leading-relaxed max-w-2xl mx-auto">
            Football is a business. The IFF model ensures that the wealth generated by the game stays with the clubs that build it.
          </p>
        </div>
      </section>

      <section className="py-20 flex-grow bg-zinc-50">
        <div className="container mx-auto px-4 max-w-5xl">

          <div className="mb-16">
            <h2 className="text-3xl font-bold mb-8 text-center">The Shareholder Model</h2>
            <div className="bg-white p-8 md:p-12 rounded-3xl shadow-lg border border-gray-200">
              <p className="text-xl text-gray-700 leading-relaxed mb-6 font-medium">
                The Indvundvundvwane Major League is registered as an independent commercial company. When your club qualifies for the Major League, you do not just get the right to play—you receive equal equity.
              </p>
              <div className="flex flex-col md:flex-row gap-6 mt-10">
                <div className="flex-1 bg-zinc-50 p-6 rounded-2xl border border-gray-100">
                  <div className="text-primary font-bold text-4xl mb-2">1/16</div>
                  <h4 className="font-bold text-lg mb-2">Equal Equity</h4>
                  <p className="text-sm text-gray-600">Each of the 16 clubs holds exactly 1/16th of the shares in the Major League company.</p>
                </div>
                <div className="flex-1 bg-zinc-50 p-6 rounded-2xl border border-gray-100">
                  <div className="text-secondary-foreground font-bold text-4xl mb-2">100%</div>
                  <h4 className="font-bold text-lg mb-2">Dividend Yield</h4>
                  <p className="text-sm text-gray-600">Broadcast rights, league sponsorships, and commercial partnerships are distributed as dividends.</p>
                </div>
              </div>
            </div>
          </div>

          <h2 className="text-3xl font-bold mb-10 text-center">Business Opportunities for Club Owners</h2>
          <div className="grid md:grid-cols-3 gap-6 mb-20">
            <Card className="hover:shadow-lg transition-shadow">
               <CardContent className="p-8 text-center">
                 <Briefcase className="w-12 h-12 mx-auto text-black mb-6" />
                 <h3 className="font-bold text-xl mb-3">Real Estate Value</h3>
                 <p className="text-gray-600 text-sm">Because clubs must own their land and stadiums, you are building a tangible real estate portfolio, not just a sports team.</p>
               </CardContent>
            </Card>
            <Card className="hover:shadow-lg transition-shadow">
               <CardContent className="p-8 text-center">
                 <HandCoins className="w-12 h-12 mx-auto text-secondary-foreground mb-6" />
                 <h3 className="font-bold text-xl mb-3">Commercial Rights</h3>
                 <p className="text-gray-600 text-sm">Clubs retain full control over their matchday revenue, stadium naming rights, and localized sponsorships.</p>
               </CardContent>
            </Card>
            <Card className="hover:shadow-lg transition-shadow">
               <CardContent className="p-8 text-center">
                 <LineChart className="w-12 h-12 mx-auto text-primary mb-6" />
                 <h3 className="font-bold text-xl mb-3">Asset Appreciation</h3>
                 <p className="text-gray-600 text-sm">As the league's broadcast value grows, the value of your 1/16th share grows, allowing for high-valuation exits.</p>
               </CardContent>
            </Card>
          </div>

          <div className="border-l-4 border-black pl-8 py-4 mb-20">
             <h3 className="text-2xl font-bold mb-4">The Relegation Caveat</h3>
             <p className="text-gray-700 text-lg">
               Shares are tied to participation. If a club is relegated to the Federation League, they must forfeit their shares to the newly promoted club that takes their place. You cannot buy your way out of relegation, and you cannot retain Major League equity if you are not in the Major League. Performance guarantees value.
             </p>
          </div>

          <hr className="my-16 border-gray-200" />

          {/* Investment Marketplace */}
          <div className="mb-8">
            <div className="flex flex-col md:flex-row justify-between items-end mb-8 gap-4">
              <div>
                <span className="inline-block py-1 px-3 rounded-full bg-secondary/20 text-black font-semibold text-xs mb-3 border border-secondary/50 tracking-wider uppercase">
                  Live Platform
                </span>
                <h2 className="text-4xl font-bold">Investment Marketplace</h2>
                <p className="text-gray-600 mt-2 text-lg max-w-2xl">Browse clubs actively seeking capital to meet Major League infrastructure requirements.</p>
              </div>
              <Button variant="outline" className="text-black bg-white">View All Opportunities</Button>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              {fundingClubs.map((club, idx) => (
                <Card key={idx} className="border border-gray-200 overflow-hidden hover:shadow-xl transition-shadow">
                  <div className="bg-black text-white p-4 flex justify-between items-center">
                    <h4 className="font-bold text-lg"><Link to={`/clubs/${club.id}`} className="hover:text-blue-400 transition-colors">{club.name}</Link></h4>
                    <span className="text-xs font-bold bg-white/20 px-2 py-1 rounded-md">{club.funding!.stage}</span>
                  </div>
                  <CardContent className="p-6">
                    <div className="flex justify-between items-end mb-6 pb-6 border-b border-gray-100">
                      <div>
                        <p className="text-sm text-gray-500 mb-1">Seeking</p>
                        <p className="font-bold text-2xl text-primary">{club.funding!.seeking}</p>
                      </div>
                      <div className="text-right">
                        <p className="text-sm text-gray-500 mb-1">Offered Equity</p>
                        <p className="font-bold text-2xl">{club.funding!.equity}</p>
                      </div>
                    </div>
                    <div className="mb-6">
                      <p className="text-sm font-bold mb-2">Use of Funds</p>
                      <p className="text-gray-600 text-sm">{club.funding!.purpose}</p>
                    </div>
                    <div>
                      <div className="flex justify-between text-xs text-gray-500 mb-2">
                        <span>Funding Progress</span>
                        <span>{club.funding!.progress}%</span>
                      </div>
                      <div className="w-full bg-gray-100 rounded-full h-2 mb-6">
                         <div className="bg-primary rounded-full h-2" style={{ width: `${club.funding!.progress}%` }}></div>
                      </div>
                      <div className="flex gap-3">
                        <Button className="w-full bg-black text-white hover:bg-black/80">Request Pitch Deck</Button>
                        <Button variant="outline" className="w-full" asChild>
                           <Link to={`/clubs/${club.id}`}>View Profile</Link>
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>

        </div>
      </section>

      <section className="py-24 bg-black text-white text-center">
        <div className="container mx-auto px-4">
          <h2 className="text-4xl font-bold mb-6">Invest in the Future</h2>
          <Button size="lg" className="bg-primary text-white hover:bg-primary/90 mt-4" asChild>
             <Link to="/contact">Speak with our Business Team</Link>
          </Button>
        </div>
      </section>

      <footer className="bg-black py-12 border-t border-white/10 text-center text-gray-500 mt-auto">
        <p>© {new Date().getFullYear()} Indvundvundvwane Football Federation. All rights reserved.</p>
      </footer>
    </div>
  );
}
